basePath: /
definitions:
  models.Event:
    properties:
      amount:
        type: number
      created_at:
        type: string
      event_type:
        type: string
      id:
        type: integer
      page:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Event Tracking Platform
  title: Event Platform API
  version: "1.0"
paths:
  /events:
    get:
      description: Returns all saved events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
      summary: Get all events
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Send event to Kafka
      parameters:
      - description: Event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - text/plain
      responses:
        "200":
          description: event sent to kafka
          schema:
            type: string
        "400":
          description: invalid request
          schema:
            type: string
      summary: Create event
      tags:
      - events
swagger: "2.0"
